/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../routes/__root'
import { Route as ProtectedRouteImport } from './../../../routes/_protected'
import { Route as ProtectedIndexRouteImport } from './../../../routes/_protected/index'
import { Route as AuthAuthRouteImport } from './../../../routes/auth/_auth'
import { Route as ProtectedUsersRouteImport } from './../../../routes/_protected/users'
import { Route as ProtectedQrRouteImport } from './../../../routes/_protected/qr'
import { Route as ProtectedProductsRouteImport } from './../../../routes/_protected/products'
import { Route as AuthAuthSignupRouteImport } from './../../../routes/auth/_auth/signup'
import { Route as AuthAuthLoginRouteImport } from './../../../routes/auth/_auth/login'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQrRoute = ProtectedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProductsRoute = ProtectedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthAuthSignupRoute = AuthAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/products': typeof ProtectedProductsRoute
  '/qr': typeof ProtectedQrRoute
  '/users': typeof ProtectedUsersRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/signup': typeof AuthAuthSignupRoute
}
export interface FileRoutesByTo {
  '/products': typeof ProtectedProductsRoute
  '/qr': typeof ProtectedQrRoute
  '/users': typeof ProtectedUsersRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/signup': typeof AuthAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/products': typeof ProtectedProductsRoute
  '/_protected/qr': typeof ProtectedQrRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/auth/_auth/login': typeof AuthAuthLoginRoute
  '/auth/_auth/signup': typeof AuthAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/products'
    | '/qr'
    | '/users'
    | '/auth'
    | '/'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/products'
    | '/qr'
    | '/users'
    | '/auth'
    | '/'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/products'
    | '/_protected/qr'
    | '/_protected/users'
    | '/auth/_auth'
    | '/_protected/'
    | '/auth/_auth/login'
    | '/auth/_auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/qr': {
      id: '/_protected/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof ProtectedQrRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/products': {
      id: '/_protected/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProtectedProductsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/_auth/signup': {
      id: '/auth/_auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/auth/_auth/login': {
      id: '/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthAuthRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProductsRoute: typeof ProtectedProductsRoute
  ProtectedQrRoute: typeof ProtectedQrRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProductsRoute: ProtectedProductsRoute,
  ProtectedQrRoute: ProtectedQrRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
